
server:
  port: 8081

spring:
  application:
    name: summherum
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/summherumdb
    driverClassName: org.h2.Driver
    username: root
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console # Erreichbar unter http://localhost:8081/h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

    hibernate:
      ddl-auto: update

api:
  pexels:
    key: k02NsKSTJEfjGqKpk6J9aeGff0LTAkuJ962e3g6EgAqrJTM52xBj9yBr